--!native
--[[
    LuauRegExp
    A full-featured regular expression engine written in pure Luau. Supports Perl/PCRE2 syntax including lookaround, atomic groups, backreferences, named captures, and Unicode. Ships with a grep module for searching text and codebases.
    
    This script is NOT intended to be modified.
    To view the source code, see the 'src' folder on the official GitHub repository!

    Authors: upio
    GitHub: https://github.com/notpoiu/LuauRegExp
--]]

